-------------------------------------------------------------------------------
Test set: peerEval.PeerEvalTest
-------------------------------------------------------------------------------
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.207 s <<< FAILURE! - in peerEval.PeerEvalTest
check_inserts(peerEval.PeerEvalTest)  Time elapsed: 0.055 s  <<< FAILURE!
java.lang.AssertionError: should now be 10 expected:<10> but was:<0>
	at peerEval.PeerEvalTest.check_inserts(PeerEvalTest.java:83)

